language: cpp
cache: ccache
addons:
    apt:
        update: true
        packages: &basic_deps
            - xorg-dev
            - python3-yaml
            - liblua5.1-0-dev # strictly speaking, only BUILD_ALL builds
            - liblua5.1-0-dbg
            - gdb

git:
    submodules: false

# the rest of the build matrix, specifying each combo directly. Anything
# without explicit addons here will uses *basic_deps above, and any addons list
# overrides the global one.
jobs:
    include:
        - os: linux
          dist: xenial
          compiler: gcc
        - os: linux
          dist: xenial
          compiler: clang
        - os: windows

before_install:
- iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
- iflin "wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -"
- iflin sudo apt-add-repository "'deb https://apt.kitware.com/ubuntu/ xenial main'"
- iflin sudo apt-get update
- iflin sudo apt-get install cmake
- iflin cmake --version
- iflin which cmake
- iflin echo $PATH
- iflin /usr/bin/cmake --version
- iflin /usr/local/bin/cmake --version

install:
- git fetch --unshallow
- git submodule update --init --recursive

script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_ALL_DEPS_FROM_CONTRIB=1 ../crawl-ref
- cat CMakeFiles/CMakeOutput.log
- cat CMakeFiles/CMakeError.log
- cmake --build . --config Debug --target all
- cmake --build . --config Debug --target monster

notifications:
    email:
        on_success: change
        on_failure: always
#        recipients:
#          - crawl-ref-commits@lists.sourceforge.net
# the IRC channel name (chat.freenode.net##crawl-dev) is encrypted so that
# forks won't spam ##crawl-dev.
# See: https://github.com/travis-ci/travis-ci/issues/1094
# and https://docs.travis-ci.com/user/encryption-keys/
    irc:
        channels:
           - secure: "bZx+ynE2xu+XAuMDSxMfk9WrWpGuetYmJ7bYZfyEePCo2RZNMla1ehFof/srnFuC+KyK6E2gNpUsU4HAyySb7n20AdZxcXFaHQmQvnSU6pUEyLRifgBy7Rsn6DbI3mrsEDhiOECFIxYj2f63nsO5dkRJBQLYQwf/czAQH/0aylw="
        on_success: change
        on_failure: always
        use_notice: true
        template:
            - "%{message} (%{branch} - %{commit} #%{build_number} : %{author}): %{build_url}"
