language: cpp
cache:
    - ccache
    directories:
    - $HOME/AppData/Local/Temp/chocolatey
    - /C/tools/msys64
addons:
    apt:
        update: true
        packages: &basic_deps
            - xorg-dev
            - python3-yaml
            - liblua5.1-0-dev # strictly speaking, only BUILD_ALL builds
            - liblua5.1-0-dbg
            - gdb

git:
    submodules: false

# the rest of the build matrix, specifying each combo directly. Anything
# without explicit addons here will uses *basic_deps above, and any addons list
# overrides the global one.
jobs:
    include:
        - os: linux
          dist: xenial
          compiler: gcc
        - os: linux
          dist: xenial
          compiler: clang
        - os: windows

before_install:
- iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
- ifwin () { if [[ $TRAVIS_OS_NAME == windows ]]; then eval $@; fi; }

# install msys2 on windows
- |-
    case $TRAVIS_OS_NAME in
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac
- iflin export msys2=

- iflin "wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -"
- iflin sudo apt-add-repository "'deb https://apt.kitware.com/ubuntu/ xenial main'"
- iflin travis_retry sudo apt-get update
- iflin travis_retry sudo apt-get install cmake
- iflin export PATH=/usr/bin:$PATH # to get around travis's preinstalled version
- iflin cmake --version
- iflin which cmake

- iflin export CMAKE_FLAGS=
- ifwin export CMAKE_FLAGS= # -DTILE_MODE=LOCAL_TILES

- iflin export BUILD_FLAGS=-j2
- ifwin export BUILD_FLAGS=

before_cache:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        # https://unix.stackexchange.com/a/137322/107554
        $msys2 pacman --sync --clean --noconfirm
        ;;
    esac

install:
- $msys2 echo hello
#- $msys2 git fetch --unshallow
#- $msys2 git submodule update --init --recursive

script:
- $msys2 echo meow
#- $msys2 mkdir build
#- $msys2 cd build
#- $msys2 cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_ALL_DEPS_FROM_CONTRIB=1 $CMAKE_FLAGS ../crawl-ref
#- $msys2 cmake --build . --config Debug --target all -- $BUILD_FLAGS
#- $msys2 cmake --build . --config Debug --target monster -- $BUILD_FLAGS

notifications:
    email:
        on_success: change
        on_failure: always
#        recipients:
#          - crawl-ref-commits@lists.sourceforge.net
# the IRC channel name (chat.freenode.net##crawl-dev) is encrypted so that
# forks won't spam ##crawl-dev.
# See: https://github.com/travis-ci/travis-ci/issues/1094
# and https://docs.travis-ci.com/user/encryption-keys/
    irc:
        channels:
           - secure: "bZx+ynE2xu+XAuMDSxMfk9WrWpGuetYmJ7bYZfyEePCo2RZNMla1ehFof/srnFuC+KyK6E2gNpUsU4HAyySb7n20AdZxcXFaHQmQvnSU6pUEyLRifgBy7Rsn6DbI3mrsEDhiOECFIxYj2f63nsO5dkRJBQLYQwf/czAQH/0aylw="
        on_success: change
        on_failure: always
        use_notice: true
        template:
            - "%{message} (%{branch} - %{commit} #%{build_number} : %{author}): %{build_url}"
